language: node_js
node_js:
  - 6
services:
  - docker
env:
  global:
    - IGNORE_CERTS=true
<<<<<<< HEAD
=======
    - REDIS=redis://172.17.0.1:6379
>>>>>>> master
before_script:
  - ./travis/setup.sh
